apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: root-app
  source:
    path: kubernetes/apps
    repoURL: https://github.com/thevar1able/k8s.home.var1able.ru
    targetRevision: HEAD
