apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    name: in-cluster
  project: default
  source:
    path: '' 
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 30.2.0
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
        grafana:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.101.0/24,192.168.103.0/24
            hosts:
              - grafana.k8s.home.var1able.ru
            tls:
              - secretName: grafana-tls-secret
                hosts:
                  - grafana.k8s.home.var1able.ru
