apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: torrents
    name: in-cluster
  project: default
  source:
    path: charts/stable/plex
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        env:
          TZ: "Europe/Moscow"
        service:
          main:
            type: NodePort
            ports:
              http:
                nodePort: 32400
          dnla-tcp:
            enabled: true
          dnla-udp:
            enabled: true
        persistence:
          config:
            enabled: true
            accessMode: ReadWriteOnce
            size: 100M
            storageClass: sanic
          media:
            mountPath: /media
            enabled: true
            accessMode: ReadWriteOnce
            size: 3T
            storageClass: chonker       
        ingress:
          main:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              kubernetes.io/ingress.class: nginx
            hosts:
              - host: plex.k8s.home.var1able.ru
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: plex-tls-secret
                hosts:
                  - plex.k8s.home.var1able.ru
        podSecurityContext:
          supplementalGroups:
            - 303
            - 26
        resources:
          requests:
            gpu.intel.com/i915: 1
          limits:
            gpu.intel.com/i915: 1
